### ISSUE TITLE
Convert .js files into new class format

### ISSUE THREAD

**Issue by awangg** [awangg/NewTab#15]
Change files like time.js and schedule.js to the format used in links.js

**Comment by andrewward2001** [comment]
Things to note
- make sure to export the class (`export class Foo`)
- Member functions of the class are actually called methods, but need no keyword to be defined (i.e. you don't need `function` before the name to define it
- Member functions need to be called as `this.name` because there is no proper abstraction between the class and imported functions available through the HTML
- As a result of the `this` notation, either `this` or `this.function` may need to be mapped to a variable, since the `this` object might be reassigned in anonymous functions. If the anonymous function, however uses ES6 notation `() => {}`, the `this` object isn't reassigned and will still reference the class.

**Comment by awangg** [comment]
**Translated**: links.js, todo.js, schedule.js

**Comment by awangg** [comment]
Translated: title.js, hide.js

Only time.js left

**Comment by awangg** [comment]
todo.js encountered class problems -- reverted to old format
